group=sk.ainet.cartridge
version=0.1.0-SNAPSHOT

POM_URL=https://github.com/SKaiNET-developers/SKaiNET-cartridge-blueprints/
POM_LICENCE_NAME=MIT License
POM_LICENCE_URL=https://mit-license.org/
POM_LICENCE_DIST=repo
POM_DEVELOPER_ID=SKaiNET-developers
POM_DEVELOPER_NAME=SKaiNET development team
POM_DEVELOPER_URL=https://github.com/SKaiNET-developers/

org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8

android.useAndroidX=true
kotlin.mpp.applyDefaultHierarchyTemplate=true
kotlin.code.style=official
